CREATE TABLE IF NOT EXISTS post_boxes (
    owner_uuid UUID PRIMARY KEY,
    owner_name_cache VARCHAR(32) NOT NULL,
    mailbox_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    unread_count INTEGER NOT NULL DEFAULT 0 CHECK (unread_count >= 0),
    last_opened_at TIMESTAMP WITH TIME ZONE NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mail_packages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mailbox_owner_uuid UUID NOT NULL,
    sender_uuid UUID NULL,
    sender_name_snapshot VARCHAR(32) NOT NULL DEFAULT '',
    sender_type VARCHAR(16) NOT NULL,
    message_text TEXT NOT NULL DEFAULT '',
    read_state VARCHAR(16) NOT NULL DEFAULT 'UNREAD',
    lifecycle_state VARCHAR(16) NOT NULL DEFAULT 'AVAILABLE',
    request_id UUID NULL,
    claim_token UUID NULL,
    version INTEGER NOT NULL DEFAULT 0 CHECK (version >= 0),
    source_plugin VARCHAR(64) NULL,
    admin_note TEXT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at TIMESTAMP WITH TIME ZONE NULL,
    claim_started_at TIMESTAMP WITH TIME ZONE NULL,
    claimed_at TIMESTAMP WITH TIME ZONE NULL,
    expires_at TIMESTAMP WITH TIME ZONE NULL,
    deleted_at TIMESTAMP WITH TIME ZONE NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (expires_at IS NULL OR expires_at > created_at),
    CHECK (claimed_at IS NULL OR claim_started_at IS NOT NULL)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_mail_packages_request_id
    ON mail_packages(request_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_mail_packages_claim_token
    ON mail_packages(claim_token);

CREATE INDEX IF NOT EXISTS idx_mail_packages_owner_inbox
    ON mail_packages(mailbox_owner_uuid, lifecycle_state, read_state, created_at DESC);

CREATE TABLE IF NOT EXISTS mail_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    package_id BIGINT NOT NULL,
    slot_index INTEGER NOT NULL CHECK (slot_index >= 0),
    item_kind VARCHAR(16) NOT NULL,
    material_key VARCHAR(64) NULL,
    display_name TEXT NULL,
    amount INTEGER NOT NULL CHECK (amount > 0),
    store_id VARCHAR(128) NULL,
    unique_key VARCHAR(128) NULL,
    base64_item TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (package_id, slot_index)
);

CREATE INDEX IF NOT EXISTS idx_mail_items_package_id
    ON mail_items(package_id, slot_index);
