CREATE TABLE IF NOT EXISTS mail_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    package_id BIGINT NOT NULL,
    actor_uuid UUID NULL,
    actor_name_snapshot VARCHAR(32) NOT NULL DEFAULT '',
    actor_type VARCHAR(16) NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    payload_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_mail_events_package_id_created_at
    ON mail_events(package_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_mail_events_actor_uuid_created_at
    ON mail_events(actor_uuid, created_at DESC);
