name: RookiePostBox
version: '${project.version}'
main: com.cuzz.rookiepostbox.RookiePostBox
api-version: '1.20'
depends:
  - OdalitaMenus
  - RookieFonts
commands:
  RookiePostBox:
    permission: RookiePostBox.*